### ISSUE TITLE
favicon not showing up

### ISSUE THREAD

**Issue by MeganerdNL** [danzinger/grav-theme-vela#10]
The default favicon.png in `/user/themes/vela/images` is not showing up. Also, when I change it to another png, (16x16 or 32x32) it also is not showing up. 

I cleared cache of Grav and the browser.

Is there a setting for this?

**Comment by danzinger** [comment]
Thanks! There was a missing reference to the favicon in the code. I released an update with a fix. Favicon placed in `vela/images/` as `favicon.png` should now show up.
