### ISSUE TITLE
Setting overall font-size?

### ISSUE THREAD

**Issue by chrothenbach** [danzinger/grav-theme-vela#11]
I am creating a simple page, but the overall font-size is too big, on every element. I can't seem to figure out how to change the base font size. I tried adding to the custom.css file, but haven't been able to change that. Any advice is greatly appreciated!

**Comment by danzinger** [comment]
Hello! Thanks for using Vela! Short answer: Just set your desired font-size specifically for your element in `css-compiled/custom.css`. So if you like to have all `<p>`'s to be 10px, you just write `p{font-size:10px;}`. Of course you can also use a custom selector. Everything in `custom.css` will override the theme's standards.

The theme has no base-font-size as text is resized automatically based on the screen-size. This is to provide good reading experience on all screen sizes. Actually I recommend that you do not set a fixed font-size. There might be better ways to solve your problem. If you provide a link and explain your problem in more detail I can have a look.

**Comment by chrothenbach** [comment]
Hi,

Thanks for getting back to me. I should have been more specific. I am only going to display these pages in desktop browsers. 


> Hello! Thanks for using Vela! Short answer: Just set your desired font-size specifically for your element in `css-compiled/custom.css`. So if you like to have all `<p>`'s to be 10px, you just write `p{font-size:10px;}`. Of course you can also use a custom selector. Everything in `custom.css` will override the theme's standards.
> 
> The theme has no base-font-size as text is resized automatically based on the screen-size. This is to provide good reading experience on all screen sizes. Actually I recommend that you do not set a fixed font-size. There might be better ways to solve your problem. If you provide a link and explain your problem in more detail I can have a look.

Your suggestion worked but only under certain document types and I think I know why, I changed font-size for `p`  and `h1`, which were displaying too large for the amount of content that I was interested in having in the pages, but the change only affects the a particular document type (default.html.twig). I think I had a separate document type (docs.html.twig) that I think I copied from the learn2 theme (sorry, I may have bastardized the theme completely and made it a mix of a bunch of other themes).    

Thanks for providing this theme, it worked best for my application from several I tried!

**Comment by danzinger** [comment]
Sorry for getting back so late. Yes, in your `docs.html.twig` there was no reference to the `custom.css` file. Thats why your changed had no effects on content on these document types (=templates). Glad you like the Vela Theme :-) Let me know if you face any other problem.
