### ISSUE TITLE
adding search bar as rana theme

### ISSUE THREAD

**Issue by ufukayyildiz** [danzinger/grav-theme-vela#18]
hi,
thanks for this theme.

How can i add search bar to this theme as rana theme?

thank you.

**Comment by danzinger** [comment]
Hello! Very sorry for this late reply. I am super busy in my day job. The Vela-Theme currently has no support for the search bar, like the [Rana-Theme](https://github.com/danzinger/grav-theme-rana) (which means it is not as "integrated" in the theme). You can, however, just install the [TNT-Search Plugin](https://github.com/trilbymedia/grav-plugin-tntsearch) and use the provided Search Template on a certain page. Then you have the same search functionality with this theme.
